name = "TestSetExtensions"
uuid = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"
version = "4.0.3"
authors = ["Spencer Russell", "Phillip Alday"]

[deps]
DeepDiffs = "ab62b9b5-e342-54a8-a765-a90f495de1a6"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Aqua = "0.8"
DeepDiffs = "1"
Distributed = "1"
EzXML = "1"
Logging = "1"
MetaTesting = "=0.1.0"
Suppressor = "0.2"
Test = "1"
TestReports = "1.4"
julia = "1.10"

[weakdeps]
TestReports = "dcd651b4-b50a-5b6b-8f22-87e9f253a252"

[extensions]
TestSetExtensionsTestReportsExt = ["TestReports"]

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MetaTesting = "9e32d19f-1e4f-477a-8631-b16c78aa0f56"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
TestReports = "dcd651b4-b50a-5b6b-8f22-87e9f253a252"

[targets]
test = ["Suppressor", "Logging", "MetaTesting", "Aqua", "TestReports", "EzXML"]
